name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install sphinx
        pip install -r ./python/requirements.txt  # If you have a requirements.txt with dependencies

    - name: Build documentation
      run: |
        cd Documentation
        make html
        

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'  # Only deploy from the main branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Documentation/build/html
